### PR TITLE
Conversion to Polymer 1.0

### PR DESCRIPTION
**Pull request by Whyser**
Some parts of this conversion are not "pretty", but I still think it's better than the existing one for one simple reason: Polymer 0.5 is deprecated.

For example, since they removed support for string concentation (example: class="status {{status}}" will not work). They no longer suggest using /deep/ etc for styling if the object has custom variables. For that reason there is some styling inside the main document (for now). Also, I haven't created a minified version of the app.js and the lite.html has not been updated.

For some odd reason, the time-elements won't work. Can't understand why, if I provide a correct DateTime ISO String it will work, but it won't take the {{timestamp}} (or any other value for that matter - Polymer 1.0 issue?).

Maybe a Pull Request isn't relevant here? Maybe you guys could clone it and make a Polymer 1.0 repo?

Thanks anyway for a great tutorial/example, learned a lot needed knowledge about migrating from 0.5 to 1.0!

### CODE REVIEW

**Comment by girliemac** [comment]
Greeeeat!
I know I am way overdue for this upgrade, and always wanted to re-create one for 1.0.

Since 1.0 is almost completely different from 0.5, also this repo is linked from my tutorial, I am going to create a new repo.
I think I will try to learn the changes from your PR, and write a new article about 0.5 to 1.0 migration.

Oh, and the reason the timestamp fails is because I am using the 3rd party element, actually cretaed by GitHub. These guys need to upgrade their `<time>` element to 1.0 so I can use it.
https://github.com/github/time-elements
Or maybe you can help them out ;-)

Thank you so much, Whyser. You rock :gem:

**Comment by Whyser** [comment]
Sounds great about the new article! I will try to comment on the most obvious changes, when I get the time, so that they are not missed. :)

I skimmed through their time-elements.js and they don't seem to actually use Polymer-specific code, meaning I can't really find what is wrong. :( They basically only read the attributes on the element as far as I can see.

**Comment by Whyser** [comment]
As you can see by the commits, the time-elements issue has been fixed (needed to use the new '$='-operator). Also added some comments in various places in the code briefly explaining what has changed from the original, of course you also should read all the change log on the Polymer webpage. :)

Closing this pull request now. Happy coding!

**Comment by girliemac** [comment]
:+1: :heart:

**Pull request closed without merging**
